### ISSUE TITLE
following the default setup

### ISSUE THREAD

**Issue by Midnighter** [juliabase/juliabase#2]
Hi, very new to this project and just tried to set up my own running server. I tried following the steps on installation and programming and came across a few problems:

1. The programming guide does not mention that the `settings.py` file needs to be changed. I have created #1 in order to alleviate this problem but it probably could be expanded.
2. I would add to the installation part that juliabase runs on Django 1.7, the newest is 1.8 and I was unable to run the `manage.py` script with it.
3. The step `./manage.py collectstatic` produced the following message:

```
You have requested to collect static files at the destination
location as specified in your settings:

    /var/www/juliabase/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel:
```

I ignored this step for now and was still able to run the server (not everything tested, of course). I guess this is only needed when running Apache and the static files should be found in an accessible directory.

**Comment by bronger** [comment]
Sorry that I could not look earlier into your issues.  Thank you for the comments!  I will change the documentation and the code accordingly tomorrow.  Is the migration problem this "preserve_default" thing?  I observed that myself at least.

**Comment by Midnighter** [comment]
My bad, I've updated the above comment, I meant to write `manage.py`, of course, and not `migrate.py`. My problem with the migration was simply to correct the database settings. Maybe including a link to https://docs.djangoproject.com/en/1.7/intro/tutorial01/#database-setup in the new paragraph in #1 is sufficient.

**Comment by bronger** [comment]
Okay, I comment concretely now on your three points:

1. I merged your PR and amended it a bit.  Thank you!
2. I declared explicitly in the docs that the current release of JuliaBase works with Django 1.7, see http://www.juliabase.org/programming/installation.html#django
3. You can sefely say "yes" at this point.  You can suppress this warning with the --noinput option.  By the way, more often the problem with `collectstatic` is lecking of write permissions for the static files.

**Comment by Midnighter** [comment]
Thanks, that answers everything.
