### ISSUE TITLE
loaddata demo_accounts fail due to a nullpassword

### ISSUE THREAD

**Issue by msincan** [juliabase/juliabase#4]
```
username@server:~/myproject$ ./manage.py loaddata demo_accounts
```
results in error 

```
Could not load auth.User(pk=2): null value in column "password" violates not-null constraint
DETAIL:  Failing row contains (2, null, null, f, nobody, , Nobody, , f, t, 2015-06-05 20:17:41.653563+02).
```

I can fix this by copying the password hash of another demo account but the default repo fails as is.

**Comment by bronger** [comment]
I cannot reproduce it here.  Besides, the password is not empty for "nobody", but it is "!".

**Comment by msincan** [comment]
You are right, the password is "!" but it still results in the error I got on my end. It may be the version of PostGres? Is there a reason for not having "12345" as the password for "nobody"?

**Comment by bronger** [comment]
The reason is that one should be unable to login as "nobody".  "!" as the password is the Django way to define a password as invalid, making a login impossible.

I don't think it is PostgreSQL.  I have no idea what may cause this issue.

**Comment by msincan** [comment]
In that case, I will try to troubleshoot it more and hopefully come up with an answer.

**Comment by knightsbdh** [comment]
I can confirm this problem. I solved it by altering the "password" column of "auth_user" table to allow "NULL". I did this using phppgadmin, although I'm sure there are many ways to do it.

**Comment by bronger** [comment]
Possibly, you use a different YAML parser version?  Does quoting the exclamation mark in double quotes help?

**Comment by bronger** [comment]
I reopen for waiting for confirmation that it actually fixes the problem.
